# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/ENSC462/github/GitHub/sources/top.xdc

# Block Designs: bd/top/top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_axi_iic_0_0/top_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_iic_0_0 || ORIG_REF_NAME==top_axi_iic_0_0} -quiet] -quiet

# IP: bd/top/ip/top_clk_wiz_0_0/top_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_clk_wiz_0_0 || ORIG_REF_NAME==top_clk_wiz_0_0} -quiet] -quiet

# IP: bd/top/ip/top_ila_0_0/top_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ila_0_0 || ORIG_REF_NAME==top_ila_0_0} -quiet] -quiet

# IP: bd/top/ip/top_proc_sys_reset_0_0/top_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_proc_sys_reset_0_0 || ORIG_REF_NAME==top_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/top/ip/top_processing_system7_0_0/top_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_processing_system7_0_0 || ORIG_REF_NAME==top_processing_system7_0_0} -quiet] -quiet

# IP: bd/top/ip/top_ps7_axi_periph_0/top_ps7_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ps7_axi_periph_0 || ORIG_REF_NAME==top_ps7_axi_periph_0} -quiet] -quiet

# IP: bd/top/ip/top_I2S_audio_interface_0_0/top_I2S_audio_interface_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_I2S_audio_interface_0_0 || ORIG_REF_NAME==top_I2S_audio_interface_0_0} -quiet] -quiet

# IP: bd/top/ip/top_auto_pc_0/top_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_pc_0 || ORIG_REF_NAME==top_auto_pc_0} -quiet] -quiet

# XDC: d:/ENSC462/github/GitHub/audio_pass_through/audio_pass_through.gen/sources_1/bd/top/top_ooc.xdc
